In [2]:
from env import *

import tensorflow as tf
from ray.rllib.algorithms import dqn, ppo

In [3]:
%load_ext autoreload
%autoreload 2

tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Metal device set to: Apple M1


True


systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



In [4]:
n_disks = 5
env_config = {
    'n_disks': n_disks,
    'max_n_steps': 2 * (2 ** n_disks)
}

config = ppo.PPOConfig()
config = config.rollouts(num_rollout_workers=3)
config = config.framework('tf')

config = config.environment(HanoiTower, env_config=env_config)
agent = config.build()
agent.train()

2023-03-11 16:10:00,516	INFO worker.py:1553 -- Started a local Ray instance.


(RolloutWorker pid=19733) Metal device set to: Apple M1
(RolloutWorker pid=19733) 
(RolloutWorker pid=19733) systemMemory: 16.00 GB
(RolloutWorker pid=19733) maxCacheSize: 5.33 GB
(RolloutWorker pid=19733) 
(RolloutWorker pid=19735) Metal device set to: Apple M1
(RolloutWorker pid=19735) 
(RolloutWorker pid=19735) systemMemory: 16.00 GB
(RolloutWorker pid=19735) maxCacheSize: 5.33 GB
(RolloutWorker pid=19735) 
(RolloutWorker pid=19734) Metal device set to: Apple M1
(RolloutWorker pid=19734) 
(RolloutWorker pid=19734) systemMemory: 16.00 GB
(RolloutWorker pid=19734) maxCacheSize: 5.33 GB
(RolloutWorker pid=19734) 


(RolloutWorker pid=19733) 2023-03-11 16:10:04,698	WARNING utils.py:161 -- `config.auto_wrap_old_gym_envs` is activated AND you seem to have provided an old gym-API environment. RLlib will therefore try to auto-fix the following error. However, please consider switching over to the new `gymnasium` APIs:
(RolloutWorker pid=19733) Your environment ({}) does not abide to the new gymnasium-style API!
(RolloutWorker pid=19733) From Ray 2.3 on, RLlib only supports the new (gym>=0.26 or gymnasium) Env APIs.
(RolloutWorker pid=19733) {}
(RolloutWorker pid=19733) Learn more about the most important changes here:
(RolloutWorker pid=19733) https://github.com/openai/gym and here: https://github.com/Farama-Foundation/Gymnasium
(RolloutWorker pid=19733) 
(RolloutWorker pid=19733) In order to fix this problem, do the following:
(RolloutWorker pid=19733) 
(RolloutWorker pid=19733) 1) Run `pip install gymnasium` on your command line.
(RolloutWorker pid=19733) 2) Change all your import statements in your

In [ ]:
env = HanoiTower(config={'n_disks': 5})

In [ ]:
env.action_space.sample()

array([1, 0])

In [6]:
obs = env.reset()
env.observation_space.contains(obs)

True

In [7]:
obs

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [8]:
env.step([0, 1])

64


(array([[0, 2, 3, 4, 5],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]], dtype=int32),
 -1,
 False,
 {})